### ISSUE TITLE
利用unit_vocoder生成的音调

### ISSUE THREAD

**Issue by XiaoYuanJun-zy** [RanaCM/DSU-AVO-Samples#2]

**Comment by RanaCM** [comment]
Sorry for the late reply. Our unit vocoder is trained without f0 conditioning in a single-speaker setting. You may add f0 conditioning (following the original speech-resynthesis repo) for better controllability on pitch.

**Comment by XiaoYuanJun-zy** [comment]
> Sorry for the late reply. Our unit vocoder is trained without f0 conditioning in a single-speaker setting. You may add f0 conditioning (following the original speech-resynthesis repo) for better controllability on pitch.

I'm sorry, I didn't notice this detail before. Excellent work indeed, and thank you very much for your reply
